### ISSUE TITLE
Error on instalation

### ISSUE THREAD

**Issue by raphamorim** [tj/node-prune#1]
I love the idea from the project! I'm trying to install it and is returning error :(

```bash
$ go get -u github.com/tj/node-prune/cmd/node-prune
```

```
src/github.com/tj/node-prune/cmd/node-prune/main.go:50: time.Since(start).Round undefined (type time.Duration has no field or method Round)
```

**Comment by tj** [comment]
ahh make sure you're on a newer version of Go, I think that was added in 1.8

**Comment by raphamorim** [comment]
nice! I'll try with 1.8 👍

**Comment by raphamorim** [comment]
Worked :octocat: 
thanks @tj

**Comment by Tazeg** [comment]
Same error with : go version go1.8.3 linux/amd64

**Comment by raphamorim** [comment]
for me worked with `go version go1.9.2 darwin/amd64`
