### ISSUE TITLE
command not found: node-prune

### ISSUE THREAD

**Issue by maczyt** [tj/node-prune#10]
``` shell
$ go get github.com/tj/node-prune/cmd/node-prune
$ node-prune
// command not found: node-prune
```

**Comment by maczyt** [comment]
go version go1.9.2 darwin/amd64

**Comment by tj** [comment]
ah I forgot that $GOPATH/bin should be in your $PATH, that's one thing you have to set up after you install Go if you want to install binaries this way

**Comment by maczyt** [comment]
nice~~ It's really helpful！
