### ISSUE TITLE
go get fails on go 1.7 - type time.Duration has no field or method Round)

### ISSUE THREAD

**Issue by klauern** [tj/node-prune#13]
I can `go get` this fine on my Arch distro, but on my Win10 box, it fails:

```
~> go get github.com/tj/node-prune/cmd/node-prune
# github.com/tj/node-prune/cmd/node-prune
dev\golang\src\github.com\tj\node-prune\cmd\node-prune\main.go:50: time.Since(start).Round undefined (type time.Duration has no field or method Round)
```

**Comment by klauern** [comment]
I think that it's more due to the version of go I'm running on Windows: 1.7.4.  I'll see if I can run it on a later version and get it to work.

**Comment by tj** [comment]
yep make sure you have a more recent Go #1

**Comment by klauern** [comment]
Gah, that was it.  I put `1.9.2` on and it works just fine.  I'll close it.
