### ISSUE TITLE
node-prune commando not found with go path set

### ISSUE THREAD

**Issue by developersoul** [tj/node-prune#14]
Hi TJ, I have installed already go and I export the path to, go bin but node prune isn't on my shell 
yet.

```
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin 
```

so what more I have to do?

Thanks.

**Comment by appleboy** [comment]
1. add the following to your `.bashrc`

```
PATH=$PATH:$GOROOT/bin:$GOPATH/bin 
```

2. install node-prune with go command

```
$ go get -u github.com/tj/node-prune
```

you can find the `node-prune` file in `$GOPATH/bin` folder.

**Comment by developersoul** [comment]
@appleboy thanks but doesn't works for me :( with zshrc

**Comment by appleboy** [comment]
@developersoul I forked this repository and release all binary for all arch. You can download the binary according to your OS version with the following link.

https://github.com/appleboy/node-prune/releases/tag/1.0.0

**Comment by bigblog** [comment]
Does the executable file appear if you run `ls $GOROOT/bin`? You should also make sure that you have permission to execute the file.

**Comment by iwestlin** [comment]
Encountered same issue.
Are you using `go version go1.9.2 darwin/amd64`?
If so, add `PATH="$PATH:$HOME/go/bin"` to `~/.zshrc` then source it.

**Comment by developersoul** [comment]
It works, thanks @iwestlin
