### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by qneyrat** [tj/node-prune#19]
Can you create release and binaries files ?

**Comment by styfle** [comment]
Steps to reproduce this bug:

```sh
$ go get github.com/tj/node-prune/cmd/node-prune
bash: go: command not found
```

**Comment by tj** [comment]
https://github.com/tj/node-prune/releases 

I'll have a better solution for this stuff soonish

**Comment by styfle** [comment]
@tj Ironically, there are two Readme.md files in the linux 64 release:

```sh
$ tar -xvzf node-prune_1.0.0_linux_amd64.tar.gz
Readme.md
Readme.md
node-prune
```

**Comment by tj** [comment]
weird
