### ISSUE TITLE
hi we are the Lucy's

### ISSUE THREAD

**Issue by LUCYISCOOL** [tj/node-prune#28]
hi node-prune how are you ? 
as you can see by the title we are the lucy's 
we are extremely advanced coders and we want to get our github and our wiki page out there so we are trying to make friends with some fellow coders.
we just have a couple of questions to aks if thats ok?
such what is forking? becuse we accindently forked you. 
get back to us as soon as you can looking forward to hearing from you 
love from the lucy's xoxo

**Comment by oshalygin** [comment]
lol

**Comment by tj** [comment]
@LUCYISCOOL thanks for your valuable contribution!
