### ISSUE TITLE
Use channels here ?

### ISSUE THREAD

**Issue by bhaskarsaraogi** [tj/node-prune#3]
how about using channels to take care of removals and waitgroup on all ? overkill probably ?
https://github.com/tj/node-prune/blob/03dd2717c9a27cc08fe86a5b0bae8654f403b464/prune.go#L163

**Comment by tj** [comment]
suuure why not :D might as well speed it up, as-is it seemed to be around ~400-500ms for a pretty big project but they certainly get much bigger
