### ISSUE TITLE
syntax error while installing

### ISSUE THREAD

**Issue by SunskyXH** [tj/node-prune#30]
![image](https://user-images.githubusercontent.com/10584186/33293188-e98323ba-d406-11e7-9526-c2ee04014c02.png)

go version go1.9.2 darwin/amd64

**Comment by SunskyXH** [comment]
It seems to be all right if I use `go get -u github.com/tj/node-prune/cmd/node-prune`

**Comment by tj** [comment]
ah yea should be ok now, I merged a typo into master!
