### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by yarossia** [tj/node-prune#35]
I am installing from root directory.Using provided command: 
`go get github.com/tj/node-prune/cmd/node-prune`

 It gives me this error: 
`go/src/github.com/tj/node-prune/cmd/node-prune/main.go:50: time.Since(start).Round undefined (type time.Duration has no field or method Round)`

**Comment by tj** [comment]
check out the Releases tab for binaries, or make sure you're on Go 1.9

**Comment by yarossia** [comment]
update to newest version helped, but still it does not working. Where is I need to install it? I'm trying to it in root directory of pc, seems like it was installed but when I'm typing `node-prude` it says: unknown command

**Comment by tj** [comment]
make sure $GOPATH/bin is in your $PATH, should fix that issue. or if you use the binaries just `cp` to `/usr/local/bin` or similar

**Comment by yarossia** [comment]
<img width="1558" alt="screen shot 2017-11-29 at 11 52 02 pm" src="https://user-images.githubusercontent.com/7397161/33400978-71c76858-d560-11e7-8433-bc986e076e39.png">

**Comment by yarossia** [comment]
still node-prune: command not found

**Comment by yarossia** [comment]
set $GOPATH to $HOME/go, helped
