### ISSUE TITLE
The image on the README is down!

### ISSUE THREAD

**Issue by oshalygin** [tj/node-prune#38]
I'll take a look and put a PR together, these are sad times!

![image](https://user-images.githubusercontent.com/7675942/33457847-b51b5c18-d5d8-11e7-8927-593a8b1160c9.png)

**Comment by tj** [comment]
hahah seems ok to me

**Comment by oshalygin** [comment]
dont make me sad @tj !  You had a glorious image before all of this! Check out the PR :)
