### ISSUE TITLE
Whats this encoding exactly ?

### ISSUE THREAD

**Issue by bhaskarsaraogi** [tj/node-prune#4]
I know this makes the text bold, but whats this encoding exactly ? Just curious :)
https://github.com/tj/node-prune/blob/03dd2717c9a27cc08fe86a5b0bae8654f403b464/cmd/node-prune/main.go#L54

**Comment by akshetpandey** [comment]
[ANSI Escape Codes](https://en.wikipedia.org/wiki/ANSI_escape_code)
